<?php

/**
 * Implementation of hook_form_system_theme_settings_alter().
 */
function dcss_ui_form_system_theme_settings_alter(&$form, $form_state) {
  // Why isn't this stored elsewhere?
  $var = $form['#parameters'][2];
  $settings = theme_get_settings($var);
  $dcss = $settings['dcss'];
  if (empty($settings['dcss_ui'])) {
    return;
  }
  $form['dcss'] = array(
    '#type' => 'fieldset',
    '#tree' => TRUE,
    '#title' => 'Dynamic CSS overrides',
    '#collapsible' => true,
    '#weight' => -1,
    //'#collapsed' => true,
  );
  foreach($settings['dcss_ui'] as $var => $info) {
    if ($info['suffix']) {
      $dcss[$var] = str_replace($info['suffix'], '', $dcss[$var]);
    }
    switch($info['type']){
      case 'slider':
        $info += array(
          'process' => array(
            'suffix' => 'px',
          ),
        );
        $info['slider_settings'] += array(
          'min' => 1,
          'max' => 400,
        );
        if (!$info['slider_settings']['width']) {
           $info['slider_settings']['width'] = $info['slider_settings']['max'] - $info['slider_settings']['min'];
        }
        if (module_exists('slider_textfield')) {
          
          $form['dcss'][$var] = array(
            '#type' => 'slider_textfield',
           	'#title' =>$info['title'],
           	'#default_value' => $dcss[$var],
            '#slider_settings' =>  $info['slider_settings'],
          );

          break;
        }
      case 'numeric':
        $form['dcss'][$var] = array(
          '#type' => 'textfield',
         	'#title' =>$info['title'],
         	'#default_value' => $dcss[$var],
         	'#size' => 10,
        ); 
        break ;
      case 'imagecache':
          $preset_options = array(''=>'None');
          foreach (imagecache_presets() as $pid => $preset) {
            $preset_options[$preset['presetname']] = $preset['presetname'];
          }
          $form['dcss'][$var] = array(
            '#type' => 'select',
            '#options' => $preset_options,
           	'#title' =>$info['title'],
           	'#default_value' => $dcss[$var],
          );
      break;
      case 'color':
      $form['dcss'][$var] = array(
        '#type' => (module_exists('colorpicker') ? 'colorpicker_' : '') . 'textfield',
       	'#title' =>$info['title'],
       	'#default_value' => $dcss[$var] ,
      ); 
      break;
    }
    if (!$form['dcss'][$var]) {
      continue;
    }
    $form['dcss'][$var] += array(
      '#dcss_info' => $info,
      '#element_validate' => array(
      ),
    );
    if ($info['suffix']) {
      $form['dcss'][$var]['#element_validate'][] = 'dcss_ui_add_suffix';
    }
  }

}

function dcss_ui_add_suffix($element, &$form_values) {
  form_set_value($element, $element['#value'] . $element['#dcss_info']['suffix'], $form_values);
}